---
kind: List
apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: datawarehouse
    name: datawarehouse
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      group: erd-services
      app: datawarehouse
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          group: erd-services
          app: datawarehouse
      spec:
        containers:
          - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_OPTIONS
              value: >
                -Dapplication.configmap=datawarehouse
                -Dvertx.metrics.options.enabled=true -Dvertx.metrics.options.registryName=prometheus
            - name: AB_JOLOKIA_OFF
              value: 'true'
            imagePullPolicy: IfNotPresent
            name: datawarehouse
            ports:
              - containerPort: 9779
                name: prometheus
                protocol: TCP
            resources:
              limits:
                cpu: '1000m'
                memory: '1Gi'
              requests:
                cpu: '250m'
                memory: '500Mi'
            securityContext:
              privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /deployments/config
              name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: datawarehouse
        serviceAccountName: datawarehouse
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: application.properties
              path: application.properties
            name: datawarehouse
          name: config
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - datawarehouse
          from:
            kind: ImageStreamTag
            name: "datawarehouse:0.0.2"
        type: ImageChange

